### PR TITLE
Added requirements.txt and added installation in README.md

### PR DESCRIPTION
**Pull request by wstierhout**

### CODE REVIEW

**Comment by jojomine** [comment]
Traceback (most recent call last):
  File "instaBrute.py", line 2, in <module>
    from mainLib import *
  File "/root/Downloads/instaBrute-master/mainLib.py", line 1, in <module>
    import mechanize
ImportError: No module named mechanize please i want to fix this !

**Comment by wstierhout** [comment]
@jojomine did you do `pip install -r requirements.txt`

You are missing the mechanize dependency.

**Comment by jojomine** [comment]
i did it but now he told me like this 
syntaxerror: non-ascii character `\xf3 in file /root/Desktop/brut3k1t/requests.py on line 1 ,but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details 
like that help please

**Comment by aleperno** [comment]
Good job on pinning versions. As soon as I'm able to test it, I'll green light it.

**Comment by HotBlinky** [comment]
4e86e8ca034742cfa0641d863448a0d27fdbdf08

**Pull request merged**
